Exercise 1

In [1]:
import torch

In [ ]:
tensor_rank1 = torch.rand(8)
print("Rank 1 Tensor: ", tensor_rank1)
print("Rank 1 Tensor Shape: ", tensor_rank1.shape)
print("Rank 1 Tensor Dimension: ", tensor_rank1.ndim)


Rank 1 Tensor:  tensor([0.9662, 0.2070, 0.6975])
Rank 1 Tensor Shape:  torch.Size([3])
Rank 1 Tensor Dimension:  1


In [19]:
tensor_rank2 = torch.rand(7, 5)
print("Rank 2 Tensor: ", tensor_rank2)
print("Rank 2 Tensor Shape: ", tensor_rank2.shape)
print("Rank 2 Tensor Dimension: ", tensor_rank2.ndim)

Rank 2 Tensor:  tensor([[0.4516, 0.3345, 0.5732, 0.0018, 0.7929],
        [0.2459, 0.9267, 0.8624, 0.3369, 0.8198],
        [0.5555, 0.9268, 0.8516, 0.8313, 0.3874],
        [0.4802, 0.8666, 0.7088, 0.1395, 0.3831],
        [0.1865, 0.6067, 0.8013, 0.1592, 0.2196],
        [0.6034, 0.9811, 0.2575, 0.9942, 0.1177],
        [0.7646, 0.1816, 0.3577, 0.7986, 0.5834]])
Rank 2 Tensor Shape:  torch.Size([7, 5])
Rank 2 Tensor Dimension:  2


In [20]:
tensor_rank3 = torch.rand(3,4,5)
print("Rank 3 Tensor: ", tensor_rank3)
print("Rank 3 Tensor Shape: ", tensor_rank3.shape)
print("Rank 3 Tensor Dimension: ", tensor_rank3.ndim)

Rank 3 Tensor:  tensor([[[0.1597, 0.6311, 0.4961, 0.1087, 0.7220],
         [0.7775, 0.5530, 0.9591, 0.4916, 0.5000],
         [0.0203, 0.8391, 0.0414, 0.4543, 0.3719],
         [0.3272, 0.6915, 0.9212, 0.9156, 0.6029]],

        [[0.7261, 0.7947, 0.3799, 0.0358, 0.8429],
         [0.6854, 0.8341, 0.9290, 0.2309, 0.4447],
         [0.7509, 0.6631, 0.5272, 0.7629, 0.9896],
         [0.4517, 0.4801, 0.9497, 0.0314, 0.6428]],

        [[0.0687, 0.9569, 0.4688, 0.2697, 0.5947],
         [0.3119, 0.2780, 0.5202, 0.8640, 0.8739],
         [0.6189, 0.4095, 0.9176, 0.4125, 0.2839],
         [0.0565, 0.0193, 0.8705, 0.1849, 0.0464]]])
Rank 3 Tensor Shape:  torch.Size([3, 4, 5])
Rank 3 Tensor Dimension:  3


Exercise 2

In [3]:
import torch

In [77]:
x = torch.tensor([-10.0, 10.0, 8.0])
x.requires_grad_(True)
print(f"X values: {x}")
print()

X values: tensor([-10.,  10.,   8.], requires_grad=True)



In [78]:
def sigmoid(x):
    return 1 / (1+ torch.exp(-x))

print(f"Sigmoid of X: {sigmoid(x)}")
print()

y_sigmoid = sigmoid(x)

y_sigmoid.sum().backward()

print(f"Sigmoid Derivative of X: {x.grad}")
print()

Sigmoid of X: tensor([4.5398e-05, 9.9995e-01, 9.9966e-01], grad_fn=<MulBackward0>)

Sigmoid Derivative of X: tensor([4.5396e-05, 4.5396e-05, 3.3524e-04])



In [79]:
print("Sigmoid Function Values:")
for i, x_val in enumerate(x):
    print(f"sigmoid({x_val.item()}) = {y_sigmoid[i].item()}")
print()

print("Derivative of Sigmoid Function Values:")
for i, x_val in enumerate(x):
    print(f"sigmoid'({x_val.item()}) = {x.grad[i].item()}")

Sigmoid Function Values:
sigmoid(-10.0) = 4.539786823443137e-05
sigmoid(10.0) = 0.9999545812606812
sigmoid(8.0) = 0.9996646642684937

Derivative of Sigmoid Function Values:
sigmoid'(-10.0) = 4.539580913842656e-05
sigmoid'(10.0) = 4.539580550044775e-05
sigmoid'(8.0) = 0.0003352376807015389


Exercise 3

In [ ]:
import torch

In [21]:
A = torch.tensor([[1,2,-3], [4,5,10]])
print("Matrix A:")
print(A)
print()

B = torch.tensor([[10,11,-2], [13, -3, 8]])
print("Matrix B:")
print(B)
print()

Matrix A:
tensor([[ 1,  2, -3],
        [ 4,  5, 10]])

Matrix B:
tensor([[10, 11, -2],
        [13, -3,  8]])



In [23]:
product = A*B
print("Element-wise Product of A and B:")
print(product)
print()

Element-wise Product of A and B:
tensor([[ 10,  22,   6],
        [ 52, -15,  80]])



In [24]:
a = 10 
b_transpose = B.T
matrix_addition = a + b_transpose
print("Matrix Addition (A + B^T):")
print(matrix_addition)

Matrix Addition (A + B^T):
tensor([[20, 23],
        [21,  7],
        [ 8, 18]])


In [22]:
print("Matrix A Transpose:")
print(A.T)
print()

print("Matrix B Transpose:")
print(B.T)
print()

Matrix A Transpose:
tensor([[ 1,  4],
        [ 2,  5],
        [-3, 10]])

Matrix B Transpose:
tensor([[10, 13],
        [11, -3],
        [-2,  8]])



Exercise 4

In [29]:
import torch

In [83]:
A = torch.tensor([[1,2,3], [4,5,6]], dtype=torch.float32)
print(A)
print()

B = torch.tensor([[10,11], [-2,0], [1, -3]], dtype=torch.float32)
print(B)
print()

tensor([[1., 2., 3.],
        [4., 5., 6.]])

tensor([[10., 11.],
        [-2.,  0.],
        [ 1., -3.]])



In [84]:
product = torch.matmul(A, B)
print("Matrix Product of A and B:")
print(product)

Matrix Product of A and B:
tensor([[ 9.,  2.],
        [36., 26.]])


In [85]:
frobenius_norm_A = torch.norm(A, p='fro')
frobenius_norm_B = torch.norm(B, p='fro')
print(f"Frobenius norm of A: {frobenius_norm_A.item()}")
print(f"Frobenius norm of B: {frobenius_norm_B.item()}")

Frobenius norm of A: 9.539392471313477
Frobenius norm of B: 15.329710006713867
